name: Build and Push Docker Image

on:
  push:
    branches:
      - master   # or "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Debug secrets
    - name: Debug secrets
      run: |
        echo "Checking secrets..."
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "❌ DOCKER_USERNAME missing"; exit 1; fi
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "❌ DOCKER_PASSWORD missing"; exit 1; fi
        echo "✅ Both secrets found"

    # Docker login
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-demo-app:latest .

    # Push image
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-demo-app:latest
